# version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bet360-postgres
    environment:
      POSTGRES_USER: bet360_user
      POSTGRES_PASSWORD: bet360_password
      POSTGRES_DB: bet360_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - bet360-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bet360_user -d bet360_db"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: