"""typed columns + updated_at server default

Revision ID: 294abf119055
Revises: 8d0c519bc6ca
Create Date: 2026-08-25 16:36:56.131183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '294abf119055'
down_revision: Union[str, None] = '8d0c519bc6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default='now()')
    op.alter_column('listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default='now()')
    op.alter_column('listings', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
