"""add listing indexes

Revision ID: 82716f4ed19a
Revises: 294abf119055
Create Date: 2026-08-26 22:18:12.547326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82716f4ed19a'
down_revision: Union[str, None] = '294abf119055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add indexes for better query performance
    
    # Index for sorting by newest listings
    op.create_index('idx_listings_created_at', 'listings', ['created_at'])
    
    # Index for city filtering (JSONB field)
    op.create_index('idx_listings_location_city', 'listings', [sa.text("(location->>'city')")])
    
    # Index for price range filtering (JSONB field)
    op.create_index('idx_listings_pricing_amount', 'listings', [sa.text("(pricing->>'amount')")])
    
    # Index for bedroom filtering (JSONB field)
    op.create_index('idx_listings_property_details_bedrooms', 'listings', [sa.text("(property_details->>'bedrooms')")])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_listings_property_details_bedrooms', table_name='listings')
    op.drop_index('idx_listings_pricing_amount', table_name='listings')
    op.drop_index('idx_listings_location_city', table_name='listings')
    op.drop_index('idx_listings_created_at', table_name='listings')
    # ### end Alembic commands ###